# Authentication errors
ERR_EMPTY_FIELD = -1
ERR_USERNAME_TAKEN = -2
ERR_USERNAME_DOESNT_EXIST = -3
ERR_WRONG_PASSWORD = -4
# HTTP errors
ERR_BAD_REQUEST = -5
ERR_METHOD_NOT_ALLOWED = -6
ERR_UNAUTHORIZED = -7
ERR_NOT_FOUND = -8
ERR_DUP_TITLE = -9
# Common return codes, not errors
WANTS_FILE = -10
SUCESSFULL_REGISTER = -11
SUCESSFULL_LOGIN = -12
SUCESSFULL_ADD = -13
SUCESSFULL_DELETE = -14
